# EnchBook
# By: ShaneBee

Options:
  Prefix: '&7[&bEnchBook&7]'

  # If safe enchants is true, you will only be able to enchant books with the max level of said enchant
  # If it is false, you can enchant to your hearts desire, and also enchant tools/weapons/armor in the anvil with them
  # Leaving this true essentially means the anvil will work in a vanilla fashion
  # This can be bypassed with the permission 'enchbook.bypass.safe'
  Safe Enchants: true

  # When enchanting an item, ignore conflicting enchants (ex: smite + sharpness)
  Ignore Conflicts: false

  # If safe books is true, players will not be able to join 2 of the same books (which would increase the level by 1)
  # to increase the level over the max possible level for that enchant.
  # This also blocks creating new books with the '/enchbook newbook' that have higher than vanilla max levels.
  # This can be bypassed with the permission 'enchbook.bypass.safe'
  Safe Books: true

  # Max level when combining book enchants
  # This can be bypassed with the permission 'enchbook.bypass.max_level'
  Max Levels:
    # Protection
    #protection: 6

  # Require permission when a player attempts to combine two books and the level goes higher than vanilla allows
  # This setting only works when 'Safe Books' is false
  # This can be bypassed with the permission 'enchbook.bypass.vanilla_max_level'
  Above Vanilla Requires Permission: false

  # Require permission when a player attempts to combine an item and book and the level goes higher than vanilla allows
  # This can be bypassed with the permission 'enchbook.bypass.vanilla_max_level_item'
  Above Vanilla Item Requires Permission: false

Messages:
  # VARIABLES FOR MESSAGES:
  # {ench} = Enchantment
  # {level} = Level of Enchantment
  Create New Book: '&aYou created a new enchanted book with &b{ench} {level}'
  Added Enchant: '&aYou have successfully added &b{ench} {level} &ato your book'
  Removed Enchant: '&aYou have successfully removed &b{ench} &afrom your book'
  No Permission: '&cYou do not have permission to use this command'
