name: EnchBook
main: tk.shanebee.enchBook.EnchBook
version: '${project.version}'
author: ShaneBee
api-version: '1.13'
website: https://github.com/ShaneBeee/EnchBook/

commands:
  enchbook:
    description: enchant a new book
    aliases: [bookench, eb, be]
    usage: /enchbook <about/add/new/reload>
    permission: enchbook.admin

permissions:
  enchbook.admin:
    description: Allows admins to use the enchbook commands
    default: op
  enchbook.bypass.safe:
    description: Allows a user to bypass safe enchants
    default: op
  enchbook.bypass.vanilla_max_level:
    description: Allows a user to bypass vanilla max level
    default: op
  enchbook.bypass.max_level:
    description: Allows a user to bypass max level
    default: op
